### ISSUE TITLE
Work with babel?

### ISSUE THREAD

**Issue by wordyallen** [bencooling/serverless-plugin-graphiql#7]
`Unexpected token export`

```yml
//serverless.yml
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-graphiql
```

**Comment by bencooling** [comment]
SEE: https://github.com/bencooling/serverless-plugin-graphiql/pull/2#issue-204365176

serverless.yml
```yml
custom:
  graphiql:
    babelOptions:
      presets: ['es2015']
```
